//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("Fody")]
[assembly: AssemblyVersion("4.2.0")]
[assembly: AssemblyFileVersion("4.2.0")]
[assembly: AssemblyInformationalVersion("4.2.0-alpha.217")]
[assembly: AssemblyCopyright("Copyright © Fody 2015 - 2019")]

